INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('JavaScript','JavaScript, often abbreviated as JS, is a high-level, just-in-time compiled, multi-paradigm programming language that conforms to the ECMAScript specification. JavaScript has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.', 'https://www.javascript.com/', 7, 1);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('SQL', 'SQL is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS). It is particularly useful in handling structured data, i.e. data incorporating relations among entities and variables.', 'https://www.w3schools.com/sql/', 2, 1);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Cosmology', 'Cosmology is a branch of astronomy that involves the origin and evolution of the universe, from the Big Bang to today and on into the future. According to NASA, the definition of cosmology is "the scientific study of the large scale properties of the universe as a whole.', 'https://www.space.com/16042-cosmology.html', 3, 2);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Solar System', 'The Solar System is the gravitationally bound system of the Sun and the objects that orbit it, either directly or indirectly. Of the objects that orbit the Sun directly, the largest are the eight planets, with the remainder being smaller objects, the dwarf planets and small Solar System bodies.', 'https://solarsystem.nasa.gov/solar-system/our-solar-system/overview/', 9, 2);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('WW1', 'World War One – Causes. The first world war began in August 1914. It was directly triggered by the assassination of the Austrian archduke, Franz Ferdinand and his wife, on 28th June 1914 by Bosnian revolutionary, Gavrilo Princip. This event was, however, simply the trigger that set off declarations of war.', 'https://www.historyonthenet.com/world-war-one-causes-2', 10, 3);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Egypt', 'The history of Egypt has been long and wealthy, due to the flow of the Nile River with its fertile banks and delta, as well as the accomplishments of Egypts native inhabitants and outside influence. Much of Egypts ancient history was a mystery until the secrets of ancient Egyptian hieroglyphs were deciphered with the discovery and help of the Rosetta Stone. Among the Seven Wonders of the Ancient World, is the Great Pyramid of Giza. The Library of Alexandria was the only one of its kind for centuries.', 'https://www.youtube.com/watch?v=hO1tzmi1V5g', 6, 3);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Empires of Ancient Persia', 'Persia (roughly modern-day Iran) is among the oldest inhabited regions in the world. Archaeological sites in the country have established human habitation dating back 100,000 years to the Paleolithic Age with semi-permanent settlements (most likely for hunting parties) established before 10,000 BCE. The ancient kingdom of Elam in this area was among the most advanced of its time (its oldest settlement, the archaeological site of Chogha Bonut, dates to c. 7200 BCE) before parts of it were conquered by the Sumerians, later completely by the Assyrians, and then by the Medes.','https://www.youtube.com/watch?v=BJvxW0xJKxo', 5, 3);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Mathematics', 'the abstract science of number, quantity, and space. Mathematics may be studied in its own right ( pure mathematics ), or as it is applied to other disciplines such as physics and engineering ( applied mathematics ).', 'https://ca.ixl.com/?partner=google&campaign=341239025&adGroup=22932003785&gclid=CjwKCAiA3uDwBRBFEiwA1VsajCot6LSORo_rFM0Pf59v-XUbntxIUfom81sGbYsDivS4Yhc0HqbFpBoCFcAQAvD_BwE',5, 4);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Physics', 'Physics is the branch of science that deals with the structure of matter and how the fundamental constituents of the universe interact. It studies objects ranging from the very small using quantum mechanics to the entire universe using general relativity', 'https://www.khanacademy.org/science/ap-physics-1/ap-one-dimensional-motion/ap-physics-foundations/v/introduction-to-physics', 1, 4);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Genetics', 'Genetics is the study of heredity. Heredity is a biological process where a parent passes certain genes onto their children or offspring. Every child inherits genes from both of their biological parents and these genes in turn express specific traits', 'https://www.frontiersin.org/articles/10.3389/fpsyg.2019.01622/full',4, 5);

INSERT INTO resources (title, description, url, user_id, category_id) VALUES ('Evolution', 'In biology, evolution is the change in the characteristics of a species over several generations and relies on the process of natural selection.', 'https://www.youtube.com/watch?v=GhHOjC4oxh8', 8, 5);

