INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (3, 'It was really usefull I liked it.', true, 7, 1);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (2, 'Need to be careful on licensing and features. While they have done a great job in 2019 to make features available in standard edition, a lot of use cases may require the more expensive enterprise edition.', false, 2, 2);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (5, 'i used this website for my science space prodject and i realy like that it lookes so proffecional and well designd. 5/5 stars.', true, 3, 3);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (4, 'It was good but old informations.', true, 9, 4);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (2, 'they are more untold stories about it that is not mentioned here.', false, 10, 5);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (4, 'Good information it was useful.', false, 6, 6);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (2, 'it has same information as wikipedia.', false, 5, 7);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (5, 'they makes it so easy to learn the math ', true, 5, 8);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (2, 'so comlicated and ambeguse.', false, 1, 9);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (4, 'interesting, liked it.', true, 4, 10);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (5, 'I really liked it.recommend it .', true, 8, 11);
INSERT INTO comment_likes (rating, description, like_this, user_id, resource_id) VALUES (4, 'I really liked it.recommend it .', true, 8, 10);
